version: "3.1"
services:
  node-chat-app:
    container_name: node-chat-app
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=node-chat-app.local
      - VIRTUAL_PORT=3000
networks:
  default:
    external:
      name: nginx-proxy_nginx-proxy

